"""Added new fields

Revision ID: be1cb40ce95c
Revises: 
Create Date: 2025-06-25 08:05:51.619954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1cb40ce95c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('total_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('q_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('verdict', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.drop_column('q18')
        batch_op.drop_column('q10')
        batch_op.drop_column('q15')
        batch_op.drop_column('q2')
        batch_op.drop_column('q14')
        batch_op.drop_column('q5')
        batch_op.drop_column('q1')
        batch_op.drop_column('q3')
        batch_op.drop_column('q13')
        batch_op.drop_column('q17')
        batch_op.drop_column('q7')
        batch_op.drop_column('q6')
        batch_op.drop_column('q8')
        batch_op.drop_column('q11')
        batch_op.drop_column('q12')
        batch_op.drop_column('q16')
        batch_op.drop_column('q9')
        batch_op.drop_column('q4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q4', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q9', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q16', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q12', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q11', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q8', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q6', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q7', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q17', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q13', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q3', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q1', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q5', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q14', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q2', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q15', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q10', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('q18', sa.TEXT(), nullable=True))
        batch_op.drop_column('confidence')
        batch_op.drop_column('verdict')
        batch_op.drop_column('q_data')
        batch_op.drop_column('total_duration')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
