"""Create submission table

Revision ID: df65bad48fec
Revises: 
Create Date: 2025-06-25 09:54:57.460981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df65bad48fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('q_data', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
